site_name: "JSON Streams"
site_url: ""
use_directory_urls: false
theme:
  name: readthedocs
extra_css:
- stylesheet.css
nav:
- 'index.md'
- 'application.md'
- 'streams.md'
- 'merge.md'
- 'join.md'
- 'state.md'
- 'validator.md'
- 'query.md'
- 'aggregation_operators.md'
- 'aggregation_stages.md'
- 'design.md'
- 'system_variables.md'
- 'parameters.md'
- 'custom_jslt.md'
- 'sse.md'
- 'testing.md'
- 'documentation.md'
- 'telemetry.md'
- 'troubleshooting.md'
- 'serialisation.md'
- 'plugins.md'
- 'autoscaling.md'
- 'configuration.md'
- 'build.md'
- 'docker.md'
- 'cli.md'
- 'release_notes.md'
