{
 "title": "JSON Streams",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Service namespace",
    "query": {
     "query": "label_values(service_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "JES HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JES HTTP Average Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "avg by (aggregate) (http_server_average_duration_millis{service_namespace=\"$namespace\", service_name=\"jes-http\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JES HTTP Average Request Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (aggregate) (http_server_average_request_bytes{service_namespace=\"$namespace\", service_name=\"jes-http\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JES HTTP Average Response Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (aggregate) (http_server_average_response_bytes{service_namespace=\"$namespace\", service_name=\"jes-http\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JES HTTP Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (aggregate) (rate(http_server_requests_total{service_namespace=\"$namespace\", service_name=\"jes-http\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JES HTTP Requests per Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (http_request_method) (rate(http_server_requests_total{service_namespace=\"$namespace\", service_name=\"jes-http\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JES HTTP Total Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service_name) (rate(http_server_requests_total{service_namespace=\"$namespace\", service_name=\"jes-http\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JES HTTP Trace Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "limit": 200,
     "query": "{resource.service.namespace=\"$namespace\" && resource.service.name=\"jes-http\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "JSON Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "JSON Streams Message Movements",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (application) (rate(json_streams_messages_total{service_namespace=\"$namespace\", service_name=\"json-streams\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JSON Streams Total Message Movements",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(json_streams_messages_total{service_namespace=\"$namespace\", service_name=\"json-streams\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Server-sent Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "SSE Event Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(http_server_sse_events_total{service_namespace=\"$namespace\", service_name=\"sse\"}[$__rate_interval]))",
       "legendFormat": "{{aggregate}}"
      }
     ]
    },
    {
     "title": "SSE Connection Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum by (instance) (http_server_active_requests{service_namespace=\"$namespace\", service_name=\"sse\"})",
       "legendFormat": "{{aggregate}}"
      }
     ]
    },
    {
     "title": "SSE Total Connection Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum by (service_name) (http_server_active_requests{service_namespace=\"$namespace\", service_name=\"sse\"})",
       "legendFormat": "{{aggregate}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Letter Box",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Letter Box Average Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "sum by (service_name) (http_server_average_duration_millis{service_namespace=\"$namespace\", service_name=\"letter-box\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Letter Box Average Request Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (service_name) (http_server_average_request_bytes{service_namespace=\"$namespace\", service_name=\"letter-box\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Letter Box Total Request Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(http_server_requests_total{service_namespace=\"$namespace\", service_name=\"letter-box\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}